In [2]:
import numpy as np
import math

In [3]:
#Cehck validity of row/col/square
def isValid(a, size):
    return np.unique(a).size == size

#Check validity of candidate solution
def isSolution(board, boardSize):
    #Check row and cols vilidity
    for i in range(0,boardSize):
        if not isValid(board[i,],boardSize) or not isValid(board[:,i],boardSize):
            return False
        
    #Check squares validity
    for row in range(0,boardSize, squareSize):
        for col in range(0,boardSize, squareSize):
            if not isValid(board[row:row+squareSize, col:col+squareSize], squareSize):
                return False

    return True

In [4]:
#Generate candidate solution
def generateCandidateSolution(board, boardSize):
    candidate = board
    for i in range(0, boardSize):
        for j in range(0, boardSize):
            if candidate[i][j] == 0:
                candidate[i][j] = np.random.randint(boardSize) + 1
    return candidate

In [5]:
fileName = "a.txt" #input("Enter filename:")
maxTrials = 10000000 #input("Enter maximum number of trials:")

board = np.loadtxt(fileName, unpack=True)
boardSize = board.shape[0]
squareSize = int(math.sqrt(boardSize))
print("Board initial state:")
print(board)

solvedBoard = board

done = False
while not done:
    candidate = generateCandidateSolution(board, boardSize)
    maxTrials-=1
    done = isSolution(candidate, boardSize) or maxTrials == 0

if maxTrials != 0:
    print("Solution found!")
    print("\nBoard final state:")
    print(board)
else:
    print("Solution not found!")
    print("\nBoard final state:")
    print(board)


Board initial state:
[[3. 0. 1. 0.]
 [0. 1. 2. 3.]
 [0. 4. 0. 2.]
 [2. 0. 4. 1.]]
Solution not found!

Board final state:
[[3. 2. 1. 3.]
 [1. 1. 2. 3.]
 [1. 4. 3. 2.]
 [2. 4. 4. 1.]]
